### ISSUE TITLE
Config service is no longer in use 

### ISSUE THREAD

**Issue by TiagoTAlves** [DUNE-DAQ/daq-kube#145]
We are no longer using the Configuration Service

**Comment by jcpunk** [comment]
Does that mean I should drop https://github.com/DUNE-DAQ/daq-kube/tree/develop/dune_daq_services/daqconfig from the config?

**Comment by TiagoTAlves** [comment]
This is linked with the config service in microsercices too. I think we will talk about it in CCM next week.

**Comment by jcpunk** [comment]
See #155
