### ISSUE TITLE
Apply error reports schema to postgres on instantiation

### ISSUE THREAD

**Issue by bonnieking** [DUNE-DAQ/daq-kube#2]
Old pocket applied these schemas: https://github.com/DUNE-DAQ/pocket/tree/develop/manifests/postgres/sql

**Comment by jcpunk** [comment]
I'm not showing any conntent in the `AspNet` tables on NP04

```
ApplicationDbErrorReporting=# select * from "AspNetRoleClaims";
 Id | RoleId | ClaimType | ClaimValue 
----+--------+-----------+------------
(0 rows)

ApplicationDbErrorReporting=# select * from "AspNetRoles";
 Id | Name | NormalizedName | ConcurrencyStamp 
----+------+----------------+------------------
(0 rows)

ApplicationDbErrorReporting=# select * from "AspNetUserClaims";
 Id | UserId | ClaimType | ClaimValue 
----+--------+-----------+------------
(0 rows)

ApplicationDbErrorReporting=# select * from "AspNetUserLogins";
 LoginProvider | ProviderKey | ProviderDisplayName | UserId 
---------------+-------------+---------------------+--------
(0 rows)

ApplicationDbErrorReporting=# select * from "AspNetUserRoles";
 UserId | RoleId 
--------+--------
(0 rows)

ApplicationDbErrorReporting=# select * from "AspNetUserTokens";
 UserId | LoginProvider | Name | Value 
--------+---------------+------+-------
(0 rows)

ApplicationDbErrorReporting=# select * from "AspNetUsers";
 Id | UserName | NormalizedUserName | Email | NormalizedEmail | EmailConfirmed | PasswordHash | SecurityStamp | ConcurrencyStamp | PhoneNumber | PhoneNumberConfirmed | TwoFactorEnabled | 
LockoutEnd | LockoutEnabled | AccessFailedCount 
----+----------+--------------------+-------+-----------------+----------------+--------------+---------------+------------------+-------------+----------------------+------------------+-
-----------+----------------+-------------------
(0 rows)
```

**Comment by jcpunk** [comment]
The `ErrorReports` table is being managed automatically via telegraf.  So I think that is done.

https://github.com/DUNE-DAQ/daq-kube/blob/develop/dune_daq/ers/telegraf/helm-values.yml#L19

**Comment by jcpunk** [comment]
For the runconter bits I'm working with Tiago in https://github.com/DUNE-DAQ/microservices/tree/titavare/run-number.

I've suggested sqlalchemy as a framework so the application can create and manage its tables automatically.  Tiago hopes to evaluate this by end of Aug.

**Comment by bonnieking** [comment]
Ah, OK. We don't need the ASP schema anymore.

This datasource should work, it's complaining it can't connect (yesterday it said it couldn't find the table).

**Comment by jcpunk** [comment]
After playing with telegraf and ers yesterday, it looks like telegraf really wants to use datetime fields to store the timestamp and our current dashboards are using `int`.

I've reverted telegraf and things look to be back on track for ERS.

**Comment by jcpunk** [comment]
I think this is sorted with the most recent microservices image.
